name=MicroMidi
version=0.1
author=Thomas O Fredericks
maintainer=https://github.com/thomasfredericks
sentence=A micro (low on features, but fast and light) MIDI library for Arduino. 
paragraph=This library was made to take up less space but be as fast as possible.
category=Communication
url=https://github.com/thomasfredericks/MicroMidi
architectures=*
includes=MicroMidi.h